### PR TITLE
Update arpack patch for newer version of deal.II

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by aprokop** [comment]
It's a bit unclear why this patch is coming without any updates to the docker container.

**Comment by Rombur** [comment]
Because I forgot to update patch when I updated the image.

**Comment by aprokop** [comment]
Just trying to figure things out... So you used this updated patch when creating the new docker image, but then just forgot to include it with image update, correct?

**Comment by Rombur** [comment]
@aprokop No, I should have but I forgot. This patch allows to use arpack in a way that will be useful for matrix-free but right now we don't have any test.

**Comment by aprokop** [comment]
Ah, thank you. I was wondering why we did not detect the broken docker image. No test completely answers this.

**Comment by Rombur** [comment]
> No test completely answers this.

That's how we do real software development. If we don't test for it, we cannot break the testsuite!

**Pull request merged**
