### PR TITLE
Modify the license so it is recognized by github

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by aprokop** [comment]
I'm not sure that will help. I have the exact same problem with ForTrilinos where I added the license *after* creation of the project. And it's not recognized despite the default text. You can try running `licensee` and see if it picks it up. For me, it produced NCSA 64% similarity.

**Comment by Rombur** [comment]
Let's try this. I get 96% similarity with BSD. I had 64% before I remove the italic text.

**Comment by aprokop** [comment]
By the way, you need to remove `(c)`. I was told it means that the product was registered with U.S. copyright office. I think ORNL's licenses were updated the same way for open-source.

**Comment by Rombur** [comment]
Darn, it won't work. The threshold is at 98%.

**Pull request merged**
