### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Rombur**
Update CMake, OpenMPI, OpenBLAS, Trilinos and enable Anasazi, P4EST, and Arpack-ng.

### CODE REVIEW

**Comment by Rombur** [comment]
Not sure what happens here. I can't reproduce on `fetnat04` with the same image :(

**Comment by Rombur** [comment]
I think I know what's the problem. I built the image on `fetnat04` which has Volta GPU and deal.II autodetected the architecture to be `sm_70`. This of course is less than ideal for Kepler... I will rebuild the image and force `sm_35`. Hopefully, this will fix it.

**Comment by Rombur** [comment]
retest this please

**Comment by Rombur** [comment]
retest this please

**Comment by Rombur** [comment]
Great that worked. This is ready to be merged.

**Comment by dalg24** [comment]
@Rombur I suppose this is `rombur/mfmg-stack:19.05.1`, is it?

**Comment by Rombur** [comment]
yes

**Pull request merged**
