### PR TITLE
Shift eigenvalues for the agglomerate matrices to make them invertible

### PR DESCRIPTION
**Pull request by masterleinad**
Partially addresses #150 and #138. We know that the agglomerate matrices might not be invertible due to missing boundary conditions. Since we expect the underlying operator to be positive definite shifting the eigenvalues by one fixes this issue. In the end, we don't care for the eigenvalues but only for the eigenvectors for building the restriction matrix.

### CODE REVIEW

**Comment by aprokop** [comment]
I think I'm missing something here. Shifting diagonal is not the same as shifting eigenvalues.

**Comment by masterleinad** [comment]
Locally this passes for me.

**Comment by aprokop** [comment]
@masterleinad Please don't force-push opened PR, just commit on top of it.

**Comment by Rombur** [comment]
Why did you open two PR? I don't see the difference with #153

**Pull request merged**
